return
{
    "ActionCardinalSpline",
    "ActionFade",
    "ActionBlink",
    "ActionFollow",
    "ActionJump",
    "ActionRotationalSkew",
    "ActionSkew",
    "ActionScale",
    "ActionRotateBy3D",
    "ActionRotate",
    "ActionMove",
}