return 
{
    "TestArmatureNesting2",
    "TestAsynchronousLoading",
    "TestArmatureNesting",
    "TestPerformanceBatchNode",
    "TestPerformance",
    "TestChangeAnimationInternal",
    "TestUseMultiplePicture",
    "TestFrameEvent",
    "TestAnimationEvent",
    "TestDirectLoading",
}